"""Typed upstream wire-surface contracts."""

from __future__ import annotations

from eggpool.wire.ir import (
    CanonicalContentBlock,
    CanonicalEvent,
    CanonicalMessage,
    CanonicalOutputBlock,
    CanonicalRequest,
    CanonicalResponse,
    CanonicalTool,
    CanonicalToolChoice,
    CanonicalUsage,
    ReasoningIntent,
    canonical_request_from_mapping,
    canonical_request_to_mapping,
    reasoning_intent_from_mapping,
)
from eggpool.wire.registry import (
    BUILTIN_CODEC_FACTORIES,
    WireHint,
    WireProfileDefinition,
    WireRegistry,
    WireRegistryError,
    load_wire_registry,
    load_wire_registry_text,
    resolve_provider_wire_profiles,
)
from eggpool.wire.resolver import (
    CandidateRejection,
    NegotiationHandle,
    WireNegotiationResult,
    WirePreferenceEntry,
    WireProfileResolver,
    WireResolution,
)
from eggpool.wire.types import (
    AuthHeaderShape,
    ResolvedAuthShape,
    WireHeaderSpec,
    WireProfile,
    WireSurfaceName,
    render_wire_path_template,
    validate_wire_path_template,
)

__all__ = [
    "AuthHeaderShape",
    "BUILTIN_CODEC_FACTORIES",
    "ResolvedAuthShape",
    "WireHeaderSpec",
    "WireHint",
    "WireProfile",
    "WireProfileDefinition",
    "WireRegistry",
    "WireRegistryError",
    "WireSurfaceName",
    "CandidateRejection",
    "NegotiationHandle",
    "WireNegotiationResult",
    "WirePreferenceEntry",
    "WireProfileResolver",
    "WireResolution",
    "load_wire_registry",
    "load_wire_registry_text",
    "render_wire_path_template",
    "resolve_provider_wire_profiles",
    "validate_wire_path_template",
    "CanonicalContentBlock",
    "CanonicalEvent",
    "CanonicalMessage",
    "CanonicalOutputBlock",
    "CanonicalRequest",
    "CanonicalResponse",
    "CanonicalTool",
    "CanonicalToolChoice",
    "CanonicalUsage",
    "ReasoningIntent",
    "canonical_request_from_mapping",
    "canonical_request_to_mapping",
    "reasoning_intent_from_mapping",
]
